#include <srl.hpp>

#include "colision.h"

using namespace SRL::Types;
using namespace SRL::Math::Types;





/*
Tile COLISION TYPES
0 - EMPTY
1 - SOLID
2 - SLOPE UP LEFT   0,0  16,-8
3 - SLOPE UP RIGHT
4 - SLOPE DOWN LEFT
5 - SLOPE DOWN RIGHT
6 - HIGH SLOPE UP LEFT (+8 PIXEL IN HEIGHT COMPARED TO NORMAL SLOPE)
6 - HIGH SLOPE UP RIGHT (+8 PIXEL IN HEIGHT COMPARED TO NORMAL SLOPE)

8 - PLAYER SPAWN
*/